### ISSUE TITLE
Problem using tibber node 

### ISSUE THREAD

**Issue by fsamuelsson** [bisand/node-red-contrib-tibber-api#70]
I have a problem using the tibber feed node since today i get the following error

An error ocurred while trying to check if real time consumption is enabled.
{"code":"ERR_INVALID_PROTOCOL"}

I know tibber made som echanges in their API recently ? is the plugin updated to support the new API functions. I have upgraded the node to the latest version.

**Comment by bisand** [comment]
Hi,

It sounds like you could be using an outdated version.

Which version are you using? 
Can you doubble check the query url you have configured?

The latest version (v5.1.4) uses the query url to retrieve the websocket url for the feed, so that should not fail.
It would be nice if you could report back with your findings.

Thanks!

**Comment by fsamuelsson** [comment]
Hi !

I am using the latest version

***@***.***
***@***.***

Nodes trying to connect but then I get An error ocurred while trying to check if real time consumption is enabled.
{"code":"ERR_INVALID_PROTOCOL"}


Från: André Syvertsen Biseth ***@***.***>
Skickat: Thursday, 12 January 2023 18:34
Till: bisand/node-red-contrib-tibber-api ***@***.***>
Kopia: Fredrik Samuelsson ***@***.***>; Author ***@***.***>
Ämne: Re: [bisand/node-red-contrib-tibber-api] Problem using tibber node (Issue #70)


Hi,

It sounds like you could be using an outdated version.

Which version are you using?
Can you doubble check the query url you have configured?

The latest version (v5.1.4) uses the query url to retrieve the websocket url for the feed, so that should not fail.
It would be nice if you could report back with your findings.

Thanks!

**Comment by bisand** [comment]
I was able to reproduce the issue. It seems like you have wrong URI registered in your configuration node. Could it be the old, deprecated web socket URI (wss://api.tibber.com/v1-beta/gql/subscriptions). 
The new change from Tibber only require the [GraphQL Endpoint URI](https://developer.tibber.com/docs/guides/calling-api) which currently is: https://api.tibber.com/v1-beta/gql like the screenshot below:

![image](https://user-images.githubusercontent.com/376963/212168103-1d41c558-475b-43a2-9440-a8ce4dc24717.png)

The error response in the screenshot was returned when I specified wss:// instead of https://

A small bug in the node requires you to restart Node-Red URI change. I will as soon as possible release a fix for that. Meanwhile, provide correct URI and restart Node-Red.

Hope this solves your problem.

**Comment by bisand** [comment]
Leaving this open until the fix is confirmed..

**Comment by fsamuelsson** [comment]
Confirmed after restart of node-red , node connects to Tibber api .

Thanx

Från: André Syvertsen Biseth ***@***.***>
Skickat: Thursday, 12 January 2023 21:59
Till: bisand/node-red-contrib-tibber-api ***@***.***>
Kopia: Fredrik Samuelsson ***@***.***>; Author ***@***.***>
Ämne: Re: [bisand/node-red-contrib-tibber-api] Problem using tibber node (Issue #70)


Leaving this open until the fix is confirmed..
